// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnfyoJ3duBYBCcR-uam3ueVhzsCwAhSCM',
    appId: '1:804590897348:web:53ea679885c781f39e6191',
    messagingSenderId: '804590897348',
    projectId: 'magzgrowth-e18af',
    authDomain: 'magzgrowth-e18af.firebaseapp.com',
    databaseURL: 'https://magzgrowth-e18af-default-rtdb.firebaseio.com',
    storageBucket: 'magzgrowth-e18af.appspot.com',
    measurementId: 'G-R4FYF6SCN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxKCmCVTlloFXXsWguLztMAXGmVsiktI',
    appId: '1:804590897348:android:9916d37f28ebe1399e6191',
    messagingSenderId: '804590897348',
    projectId: 'magzgrowth-e18af',
    databaseURL: 'https://magzgrowth-e18af-default-rtdb.firebaseio.com',
    storageBucket: 'magzgrowth-e18af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0Up9Z9o9mf5U6uAhlZiO2wERMpYE_Yk',
    appId: '1:804590897348:ios:c713fbcc844874fd9e6191',
    messagingSenderId: '804590897348',
    projectId: 'magzgrowth-e18af',
    databaseURL: 'https://magzgrowth-e18af-default-rtdb.firebaseio.com',
    storageBucket: 'magzgrowth-e18af.appspot.com',
    androidClientId: '804590897348-bsm6bo2ur4tc4p5upargg172gab8c4mj.apps.googleusercontent.com',
    iosClientId: '804590897348-rd95dplo9m83a499uj8c9h64qggaftfi.apps.googleusercontent.com',
    iosBundleId: 'com.Ovation.magzgrowthWeb',
  );
}
